// import type { Metadata } from "next";
import "./globals.css";
import { Alex_Brush, Montserrat } from "next/font/google";

//components
import Header from '@/components/Header';
import Footer from '@/components/Footer';


// const inter = Inter({ subsets: ["latin"] });
const alexBrush = Alex_Brush({
  weight: ['400'],
  subsets: ["latin"],
  variable: '--font-alexBrush',
});
const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
  variable: '--font-monsterrat',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${alexBrush.className} ${montserrat.className} overflow-x-hidden relative`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
